### ISSUE TITLE
Cannot run Lambda Common Layer Locally - cannot import dotenv

### ISSUE THREAD

**Issue by jackrwoods** [OSU-Sustainability-Office/lambda-common-layer#21]

**Comment by kristinaxlee** [comment]
```
ERROR   Uncaught Exception      {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'dotenv'","stack":["Runtime.ImportModuleError: Error: Cannot find module 'dotenv'","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:45:30)","    at Module._compile (internal/modules/cjs/loader.js:778:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)","    at Module.load (internal/modules/cjs/loader.js:653:32)","    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)","    at Function.Module._load (internal/modules/cjs/loader.js:585:3)","    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)","    at startup (internal/bootstrap/node.js:283:19)"]}
```

issue still prevalent after running npm install dotenv

**Comment by MilanDonhowe** [comment]
Recently ran into similar issue, solved by running `npm install` locally in `dependencies/nodejs` directory with the correct node installation.  Not entirely sure why that worked since afaik we don't need to run `npm install` for the energy-layer in the dashboard but I could be misremembering.
